spring.application.name=coreservices

#Postgresql Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d8nno3ok1i2s73dhlt6g-a.oregon-postgres.render.com:5432/mth_9j50
spring.datasource.username=postgres_user
spring.datasource.password=9X1agIqA9Q49eIcDasUIXNNGFQflzhwS

#JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Port Number
server.port=8001